"use client";

import { type InvoiceTemplate } from "@/actions/invoice/schema";

const defaultTemplate: InvoiceTemplate = {
  title: "Invoice",
  customer_label: "To",
  from_label: "From",
  invoice_no_label: "Invoice No",
  issue_date_label: "Issue Date",
  due_date_label: "Due Date",
  description_label: "Description",
  price_label: "Price",
  quantity_label: "Quantity",
  total_label: "Total",
  total_summary_label: "Total",
  subtotal_label: "Subtotal",
  vat_label: "VAT",
  tax_label: "Tax",
  payment_label: "Payment Details",
  payment_details: undefined,
  note_label: "Note",
  logo_url: undefined,
  currency: "USD",
  from_details: undefined,
  size: "a4",
  include_vat: true,
  include_tax: true,
  discount_label: "Discount",
  include_discount: false,
  include_units: false,
  include_decimals: false,
  include_qr: true,
  date_format: "dd/MM/yyyy",
  tax_rate: 0,
  vat_rate: 0,
  delivery_type: "create",
  timezone: undefined,
};
